print("#########\n#\t\t#\n#\t\t#\n#\t\t#\n#########\n\n#\t\t#\n#\t\t#\n#########\n#\t\t#\n#\t\t#")
# print("#\t\t#")
# print("#\t\t#")
# print("#\t\t#")
# print("#########", end='\n')
#print("#\t\t#")
#print("#\t\t#")
#print("#########")
#print("#\t\t#")
#print("#\t\t#")